/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006d37",
        "primary-container": "#2ecc71",
        "on-primary": "#ffffff",
        "on-primary-container": "#005027",
        "secondary": "#336943",
        "secondary-container": "#b5f1c0",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#396f48",
        "tertiary": "#98472a",
        "tertiary-container": "#ff9875",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#772e14",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#f7f9ff",
        "on-background": "#091d2e",
        "surface": "#f7f9ff",
        "on-surface": "#091d2e",
        "surface-variant": "#d1e4fb",
        "on-surface-variant": "#3d4a3e",
        "outline": "#6c7b6d",
        "outline-variant": "#bbcbbb",
        "inverse-surface": "#203243",
        "inverse-on-surface": "#e8f2ff",
        "inverse-primary": "#4ae183",
        "surface-dim": "#c9dcf3",
        "surface-bright": "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf4ff",
        "surface-container": "#e3efff",
        "surface-container-high": "#d9eaff",
        "surface-container-highest": "#d1e4fb",
        // Dark mode overrides
        "dark-background": "#060e20",
        "dark-surface": "#060e20",
        "dark-on-surface": "#dee5ff",
        "dark-surface-container": "#0f1930",
        "dark-surface-container-low": "#091328",
        "dark-surface-container-high": "#141f38",
        "dark-surface-container-highest": "#192540",
        "dark-on-surface-variant": "#a3aac4",
        "dark-outline": "#6d758c",
        "dark-outline-variant": "#40485d",
        "dark-primary": "#69f6b8",
        "dark-primary-container": "#06b77f",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
